Fail spotless apply step if spotless check fails

diff --git a/.github/workflows/spotless-check.yml b/.github/workflows/spotless-check.yml
--- a/.github/workflows/spotless-check.yml
+++ b/.github/workflows/spotless-check.yml
@@ -14,11 +14,20 @@ jobs:
           java-version: "17"
           distribution: "temurin"
 
-      - run: ./gradlew spotlessCheck
+      - name: Spotless Check
+        id: spotless
+        run: |
+          ./gradlew spotlessCheck
+          echo "::set-output name=status::$?"
         continue-on-error: true
 
       - name: Spotless Apply
-        if: ${{ failure() }}
-        uses: EndBug/add-and-commit@v9
-        with:
-          default_author: github_actions
+        if: steps.spotless.outputs.status != '0'
+        run: |
+          ./gradlew spotlessApply
+          echo "Spotless check failed. Applied formatting changes."
+        continue-on-error: true
+
+      - name: Fail the Workflow
+        if: steps.spotless.outputs.status != '0'
+        run: exit 1
